/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/newhands.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="SubTool-0-8708123"
          castShadow
          receiveShadow
          geometry={nodes['SubTool-0-8708123'].geometry}
          material={materials['Default OBJ']}
          position={[1.94346094, 2.13325882, -8.34997368]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.21320796, 0.21320796, 0.21320796]}
          userData={{ name: 'SubTool-0-8708123' }}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/newhands.glb')
