/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/samplenew.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.typing.play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" userData={{ name: 'Armature' }}>
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Wolf3D_Glasses"
            geometry={nodes.Wolf3D_Glasses.geometry}
            material={materials['Wolf3D_Glasses.002']}
            skeleton={nodes.Wolf3D_Glasses.skeleton}
            userData={{ name: 'Wolf3D_Glasses' }}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials['Wolf3D_Teeth.002']}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
            userData={{
              targetNames: [
                'mouthOpen',
                'mouthSmile',
                'eyesClosed',
                'eyesLookUp',
                'eyesLookDown',
                'eyeBlinkLeft',
                'eyeSquintLeft',
                'eyeWideLeft',
                'eyeBlinkRight',
                'eyeSquintRight',
                'eyeWideRight',
                'jawForward',
                'jawLeft',
                'jawRight',
                'jawOpen',
                'mouthClose',
                'mouthFunnel',
                'mouthPucker',
                'mouthLeft',
                'mouthRight',
                'mouthSmileLeft',
                'mouthSmileRight',
                'mouthFrownLeft',
                'mouthFrownRight',
                'mouthDimpleLeft',
                'mouthDimpleRight',
                'mouthStretchLeft',
                'mouthStretchRight',
                'mouthRollLower',
                'mouthRollUpper',
                'mouthShrugLower',
                'mouthShrugUpper',
                'mouthPressLeft',
                'mouthPressRight',
                'mouthLowerDownLeft',
                'mouthLowerDownRight',
                'mouthUpperUpLeft',
                'mouthUpperUpRight',
                'browDownLeft',
                'browDownRight',
                'browInnerUp',
                'browOuterUpLeft',
                'browOuterUpRight',
                'cheekPuff',
                'cheekSquintLeft',
                'cheekSquintRight',
                'noseSneerLeft',
                'noseSneerRight',
                'viseme_sil',
                'viseme_PP',
                'viseme_FF',
                'viseme_TH',
                'viseme_DD',
                'viseme_kk',
                'viseme_CH',
                'viseme_SS',
                'viseme_nn',
                'viseme_RR',
                'viseme_aa',
                'viseme_E',
                'viseme_I',
                'viseme_O',
                'viseme_U',
              ],
              name: 'Wolf3D_Teeth',
            }}
          />
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={nodes.EyeLeft.material}
            skeleton={nodes.EyeLeft.skeleton}
            userData={{ name: 'EyeLeft' }}
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={nodes.EyeRight.material}
            skeleton={nodes.EyeRight.skeleton}
            userData={{ name: 'EyeRight' }}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials['Wolf3D_Outfit_Footwear.002']}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
            userData={{ name: 'Wolf3D_Outfit_Footwear' }}
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials['Wolf3D_Hair.002']}
            skeleton={nodes.Wolf3D_Hair.skeleton}
            userData={{ name: 'Wolf3D_Hair' }}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials['Wolf3D_Skin.002']}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
            userData={{
              targetNames: [
                'mouthOpen',
                'mouthSmile',
                'eyesClosed',
                'eyesLookUp',
                'eyesLookDown',
                'eyeBlinkLeft',
                'eyeSquintLeft',
                'eyeWideLeft',
                'eyeBlinkRight',
                'eyeSquintRight',
                'eyeWideRight',
                'jawForward',
                'jawLeft',
                'jawRight',
                'jawOpen',
                'mouthClose',
                'mouthFunnel',
                'mouthPucker',
                'mouthLeft',
                'mouthRight',
                'mouthSmileLeft',
                'mouthSmileRight',
                'mouthFrownLeft',
                'mouthFrownRight',
                'mouthDimpleLeft',
                'mouthDimpleRight',
                'mouthStretchLeft',
                'mouthStretchRight',
                'mouthRollLower',
                'mouthRollUpper',
                'mouthShrugLower',
                'mouthShrugUpper',
                'mouthPressLeft',
                'mouthPressRight',
                'mouthLowerDownLeft',
                'mouthLowerDownRight',
                'mouthUpperUpLeft',
                'mouthUpperUpRight',
                'browDownLeft',
                'browDownRight',
                'browInnerUp',
                'browOuterUpLeft',
                'browOuterUpRight',
                'cheekPuff',
                'cheekSquintLeft',
                'cheekSquintRight',
                'noseSneerLeft',
                'noseSneerRight',
                'viseme_sil',
                'viseme_PP',
                'viseme_FF',
                'viseme_TH',
                'viseme_DD',
                'viseme_kk',
                'viseme_CH',
                'viseme_SS',
                'viseme_nn',
                'viseme_RR',
                'viseme_aa',
                'viseme_E',
                'viseme_I',
                'viseme_O',
                'viseme_U',
              ],
              name: 'Wolf3D_Head',
            }}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials['Wolf3D_Outfit_Bottom.002']}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
            userData={{ name: 'Wolf3D_Outfit_Bottom' }}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top"
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials['Wolf3D_Outfit_Top.002']}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
            userData={{ name: 'Wolf3D_Outfit_Top' }}
          />
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials['Wolf3D_Body.002']}
            skeleton={nodes.Wolf3D_Body.skeleton}
            userData={{ name: 'Wolf3D_Body' }}
          />
        </group>
        <group
          name="Mcbook_Laptop"
          position={[0.12577671, 0.68675607, 0.64616787]}
          rotation={[Math.PI, -1.5e-7, Math.PI]}
          userData={{ name: 'Mcbook Laptop' }}>
          <group name="Plane" userData={{ name: 'Plane' }}>
            <mesh
              name="Plane002_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_1.geometry}
              material={materials.MB_keyboard}
            />
            <mesh
              name="Plane002_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_2.geometry}
              material={materials.MB_metal}
            />
            <mesh
              name="Plane002_3"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_3.geometry}
              material={materials['MB_metal 2']}
            />
            <mesh
              name="Plane002_4"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_4.geometry}
              material={materials['MB_gray logo']}
            />
            <mesh
              name="Plane002_5"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_5.geometry}
              material={materials.MB_desktop}
            />
            <mesh
              name="Plane002_6"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_6.geometry}
              material={materials['MB_screen black']}
            />
            <mesh
              name="Plane002_7"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_7.geometry}
              material={materials['MB_plastic 01']}
            />
            <mesh
              name="Plane002_8"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_8.geometry}
              material={materials['MB_plastic 02']}
            />
            <mesh
              name="Plane002_9"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_9.geometry}
              material={materials.MB_blue}
            />
            <mesh
              name="Plane002_10"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_10.geometry}
              material={materials['MB_metal 4']}
            />
            <mesh
              name="Plane002_11"
              castShadow
              receiveShadow
              geometry={nodes.Plane002_11.geometry}
              material={materials['MB_metal black']}
            />
          </group>
        </group>
        <group
          name="Palm_V2"
          position={[-1.03011429, -0.01286303, -0.05026361]}
          rotation={[Math.PI, -3.9e-7, Math.PI]}
          scale={[0.83188522, 0.83188522, 0.83188522]}
          userData={{ name: 'Palm V2' }}>
          <mesh
            name="Bark_1_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Bark_1_Mat.geometry}
            material={nodes.Bark_1_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Bark_1_Mat' }}
          />
          <mesh
            name="Bark_2_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Bark_2_Mat.geometry}
            material={nodes.Bark_2_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Bark_2_Mat' }}
          />
          <mesh
            name="Dead_Leaf_1_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Dead_Leaf_1_Mat.geometry}
            material={nodes.Dead_Leaf_1_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Dead_Leaf_1_Mat' }}
          />
          <mesh
            name="Dead_Leaf_1_v2_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Dead_Leaf_1_v2_Mat.geometry}
            material={nodes.Dead_Leaf_1_v2_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Dead_Leaf_1_v2_Mat' }}
          />
          <mesh
            name="Dead_Leaf_1_v3_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Dead_Leaf_1_v3_Mat.geometry}
            material={nodes.Dead_Leaf_1_v3_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Dead_Leaf_1_v3_Mat' }}
          />
          <mesh
            name="Dead_Leaf_1_v4_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Dead_Leaf_1_v4_Mat.geometry}
            material={nodes.Dead_Leaf_1_v4_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Dead_Leaf_1_v4_Mat' }}
          />
          <mesh
            name="Dead_Leaf_2_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Dead_Leaf_2_Mat.geometry}
            material={nodes.Dead_Leaf_2_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Dead_Leaf_2_Mat' }}
          />
          <mesh
            name="Leaf_1_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_1_Mat.geometry}
            material={nodes.Leaf_1_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_1_Mat' }}
          />
          <mesh
            name="Leaf_1_v2_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_1_v2_Mat.geometry}
            material={nodes.Leaf_1_v2_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_1_v2_Mat' }}
          />
          <mesh
            name="Leaf_1_v3_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_1_v3_Mat.geometry}
            material={nodes.Leaf_1_v3_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_1_v3_Mat' }}
          />
          <mesh
            name="Leaf_1_v4_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_1_v4_Mat.geometry}
            material={nodes.Leaf_1_v4_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_1_v4_Mat' }}
          />
          <mesh
            name="Leaf_2_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_2_Mat.geometry}
            material={nodes.Leaf_2_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_2_Mat' }}
          />
          <mesh
            name="Leaf_2_v2_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_2_v2_Mat.geometry}
            material={nodes.Leaf_2_v2_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_2_v2_Mat' }}
          />
          <mesh
            name="Leaf_2_v3_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_2_v3_Mat.geometry}
            material={nodes.Leaf_2_v3_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_2_v3_Mat' }}
          />
          <mesh
            name="Leaf_2_v4_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_2_v4_Mat.geometry}
            material={nodes.Leaf_2_v4_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_2_v4_Mat' }}
          />
          <mesh
            name="Leaf_3_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_3_Mat.geometry}
            material={nodes.Leaf_3_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_3_Mat' }}
          />
          <mesh
            name="Leaf_3_v2_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_3_v2_Mat.geometry}
            material={nodes.Leaf_3_v2_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_3_v2_Mat' }}
          />
          <mesh
            name="Leaf_3_v3_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_3_v3_Mat.geometry}
            material={nodes.Leaf_3_v3_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_3_v3_Mat' }}
          />
          <mesh
            name="Leaf_3_v4_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Leaf_3_v4_Mat.geometry}
            material={nodes.Leaf_3_v4_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Leaf_3_v4_Mat' }}
          />
          <mesh
            name="Twig_Mat"
            castShadow
            receiveShadow
            geometry={nodes.Twig_Mat.geometry}
            material={nodes.Twig_Mat.material}
            position={[-2.26714206, 0.02707693, 0.22837819]}
            scale={[0.10474549, 0.10474549, 0.10474549]}
            userData={{ name: 'Twig_Mat' }}
          />
        </group>
        <mesh
          name="Pot"
          castShadow
          receiveShadow
          geometry={nodes.Pot.geometry}
          material={materials.Pot}
          position={[-1.37999654, -0.01178484, -0.15486836]}
          rotation={[0, -0.5437345, 0]}
          scale={[0.10273121, 0.10273119, 0.10273121]}
          userData={{ name: 'Pot' }}>
          <mesh
            name="NurbsPath001"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath001.geometry}
            material={nodes.NurbsPath001.material}
            position={[-0.17590481, 5.44327068, -0.25891167]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={[3.0902617, 2.6444602, 2.00252724]}
            userData={{ name: 'NurbsPath.001' }}
          />
          <mesh
            name="NurbsPath002"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath002.geometry}
            material={nodes.NurbsPath002.material}
            position={[0.10543619, 4.43000889, 0.50935751]}
            rotation={[-1.6e-7, -0.7835141, Math.PI / 2]}
            scale={[2.04022479, 2.96902943, 2.94936872]}
            userData={{ name: 'NurbsPath.002' }}
          />
          <mesh
            name="NurbsPath004"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath004.geometry}
            material={nodes.NurbsPath004.material}
            position={[0.33062074, 4.63231945, -0.01648051]}
            rotation={[1.2e-7, 0.38117915, Math.PI / 2]}
            scale={[2.24987864, 2.64445949, 2.00252676]}
            userData={{ name: 'NurbsPath.004' }}
          />
          <mesh
            name="NurbsPath005"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath005.geometry}
            material={nodes.NurbsPath005.material}
            position={[-0.23109798, 5.43730211, 0.49449059]}
            rotation={[3.00743349, -1.24859239, -1.65293509]}
            scale={[3.08827901, 2.64581609, 2.00343132]}
            userData={{ name: 'NurbsPath.005' }}
          />
          <mesh
            name="NurbsPath006"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath006.geometry}
            material={nodes.NurbsPath006.material}
            position={[-0.55909437, 4.51109791, -0.09653683]}
            rotation={[Math.PI, 0.376798, -Math.PI / 2]}
            scale={[2.12425685, 3.28102422, 2.94014525]}
            userData={{ name: 'NurbsPath.006' }}
          />
          <mesh
            name="NurbsPath007"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath007.geometry}
            material={nodes.NurbsPath007.material}
            position={[0.42259693, 3.41770816, -0.34926882]}
            rotation={[6e-8, 0.91109147, Math.PI / 2]}
            scale={[0.99118412, 2.002527, 2.002527]}
            userData={{ name: 'NurbsPath.007' }}
          />
          <mesh
            name="NurbsPath008"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath008.geometry}
            material={nodes.NurbsPath008.material}
            position={[-0.00489943, 3.0499711, 0.64064467]}
            rotation={[-3.7e-7, -1.33742536, Math.PI / 2]}
            scale={[0.61009997, 1.46282017, 1.46282017]}
            userData={{ name: 'NurbsPath.008' }}
          />
          <mesh
            name="NurbsPath009"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath009.geometry}
            material={nodes.NurbsPath009.material}
            position={[-0.39578566, 3.0499711, -0.34578037]}
            rotation={[Math.PI, 0.03476778, -Math.PI / 2]}
            scale={[0.61009997, 1.46282041, 1.46282041]}
            userData={{ name: 'NurbsPath.009' }}
          />
          <mesh
            name="NurbsPath010"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath010.geometry}
            material={nodes.NurbsPath010.material}
            position={[0.46673846, 5.44327068, 0.30865398]}
            rotation={[0, -0.06365153, Math.PI / 2]}
            scale={[3.0902617, 2.64445996, 2.00252724]}
            userData={{ name: 'NurbsPath.010' }}
          />
          <mesh
            name="NurbsPath011"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath011.geometry}
            material={nodes.NurbsPath011.material}
            position={[-0.00402358, 4.43000889, -0.4511157]}
            rotation={[7e-8, 1.03280487, Math.PI / 2]}
            scale={[2.04022479, 2.96902943, 2.94936943]}
            userData={{ name: 'NurbsPath.011' }}
          />
          <mesh
            name="NurbsPath012"
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath012.geometry}
            material={nodes.NurbsPath012.material}
            position={[-0.15727897, 4.43000889, 0.31705979]}
            rotation={[-Math.PI, -0.79737942, -Math.PI / 2]}
            scale={[2.04022479, 2.96902895, 2.94936943]}
            userData={{ name: 'NurbsPath.012' }}
          />
          <mesh
            name="Dirt"
            castShadow
            receiveShadow
            geometry={nodes.Dirt.geometry}
            material={materials['Pot Dirt']}
            position={[0, 2.39779758, 0]}
            scale={[1.03988695, 1.03988683, 1.03988695]}
            userData={{ name: 'Dirt' }}
          />
          <mesh
            name="Plane002"
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={nodes.Plane002.material}
            position={[-0.20520982, 11.53047657, -0.25891143]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.21292807, 0.28118461, 0.32858655]}
            userData={{ name: 'Plane.002' }}
          />
          <mesh
            name="Plane004"
            castShadow
            receiveShadow
            geometry={nodes.Plane004.geometry}
            material={nodes.Plane004.material}
            position={[0.13589805, 8.44884968, 0.47878042]}
            rotation={[Math.PI / 2, 1.7e-7, 2.35431045]}
            scale={[0.31360546, 0.31569591, 0.21693645]}
            userData={{ name: 'Plane.004' }}
          />
          <mesh
            name="Plane008"
            castShadow
            receiveShadow
            geometry={nodes.Plane008.geometry}
            material={nodes.Plane008.material}
            position={[0.31971866, 9.06413651, -0.04368215]}
            rotation={[Math.PI / 2, 1.2e-7, 1.1896176]}
            scale={[0.21292803, 0.28118458, 0.23922887]}
            userData={{ name: 'Plane.008' }}
          />
          <mesh
            name="Plane010"
            castShadow
            receiveShadow
            geometry={nodes.Plane010.geometry}
            material={nodes.Plane010.material}
            position={[-0.36133569, 11.51018047, 0.16192295]}
            rotation={[1.51456633, 0.02598341, -2.82039695]}
            scale={[0.21302417, 0.28132877, 0.3283757]}
            userData={{ name: 'Plane.010' }}
          />
          <mesh
            name="Plane012"
            castShadow
            receiveShadow
            geometry={nodes.Plane012.geometry}
            material={nodes.Plane012.material}
            position={[-0.57492548, 8.69546413, -0.05652905]}
            rotation={[Math.PI / 2, -1.8e-7, -1.19399824]}
            scale={[0.31262469, 0.34887022, 0.22587155]}
            userData={{ name: 'Plane.012' }}
          />
          <mesh
            name="Plane014"
            castShadow
            receiveShadow
            geometry={nodes.Plane014.geometry}
            material={nodes.Plane014.material}
            position={[0.3994408, 5.3701458, -0.36722934]}
            rotation={[Math.PI / 2, 9e-8, 0.65970499]}
            scale={[0.21292807, 0.21292807, 0.10539228]}
            userData={{ name: 'Plane.014' }}
          />
          <mesh
            name="Plane016"
            castShadow
            receiveShadow
            geometry={nodes.Plane016.geometry}
            material={nodes.Plane016.material}
            position={[0.01592724, 4.25174809, 0.63569415]}
            rotation={[Math.PI / 2, 1e-8, 2.90822194]}
            scale={[0.15554121, 0.15554121, 0.06487174]}
            userData={{ name: 'Plane.016' }}
          />
          <mesh
            name="Plane018"
            castShadow
            receiveShadow
            geometry={nodes.Plane018.geometry}
            material={nodes.Plane018.material}
            position={[-0.39652976, 4.25174809, -0.32438636]}
            rotation={[Math.PI / 2, -6e-8, -1.53602861]}
            scale={[0.15554121, 0.15554121, 0.06487174]}
            userData={{ name: 'Plane.018' }}
          />
          <mesh
            name="Plane020"
            castShadow
            receiveShadow
            geometry={nodes.Plane020.geometry}
            material={nodes.Plane020.material}
            position={[0.46860224, 11.53047657, 0.27940828]}
            rotation={[Math.PI / 2, 1.2e-7, 1.63444789]}
            scale={[0.21292804, 0.28118461, 0.32858655]}
            userData={{ name: 'Plane.020' }}
          />
          <mesh
            name="Plane022"
            castShadow
            receiveShadow
            geometry={nodes.Plane022.geometry}
            material={nodes.Plane022.material}
            position={[-0.04108781, 8.44884968, -0.47323188]}
            rotation={[Math.PI / 2, 2e-8, 0.53799168]}
            scale={[0.31360549, 0.31569594, 0.21693645]}
            userData={{ name: 'Plane.022' }}
          />
          <mesh
            name="Plane024"
            castShadow
            receiveShadow
            geometry={nodes.Plane024.geometry}
            material={nodes.Plane024.material}
            position={[-0.1263959, 8.44884968, 0.34721136]}
            rotation={[Math.PI / 2, 6e-8, -2.36817597]}
            scale={[0.31360549, 0.31569591, 0.21693645]}
            userData={{ name: 'Plane.024' }}
          />
        </mesh>
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['silla.003']}
          position={[-0.15571976, 1.03635216, -0.69922155]}
          scale={[1.35307753, 1.04366577, 0.03312864]}
          userData={{ name: 'Cube' }}
        />
        <mesh
          name="Object011002"
          castShadow
          receiveShadow
          geometry={nodes.Object011002.geometry}
          material={nodes.Object011002.material}
          position={[-1.05351913, 0.02323057, 1.03537405]}
          rotation={[Math.PI / 2, -3.8e-7, -1.47416093]}
          scale={[1.04051912, 1.04051876, 1.04051876]}
          userData={{ name: 'Object011.002' }}
        />
        <mesh
          name="Import_Symbol_location_<Not_Shared>_120258"
          castShadow
          receiveShadow
          geometry={nodes['Import_Symbol_location_<Not_Shared>_120258'].geometry}
          material={nodes['Import_Symbol_location_<Not_Shared>_120258'].material}
          position={[-0.47335488, -0.00475415, 1.24948907]}
          scale={[0.28754726, 0.28754726, 0.28754726]}
          userData={{ name: 'Import Symbol location <Not Shared> [120258]' }}>
          <group
            name="Import_Symbol_location_<Not_Shared>_120258_120246"
            userData={{ name: 'Import Symbol location <Not Shared> [120258]_[120246]' }}>
            <mesh
              name="Import_Symbol_location_<Not_Shared>_120258_120243"
              castShadow
              receiveShadow
              geometry={nodes['Import_Symbol_location_<Not_Shared>_120258_120243'].geometry}
              material={nodes['Import_Symbol_location_<Not_Shared>_120258_120243'].material}
              userData={{ name: 'Import Symbol location <Not Shared> [120258]_[120243]' }}
            />
            <mesh
              name="Import_Symbol_location_<Not_Shared>_120258_120244"
              castShadow
              receiveShadow
              geometry={nodes['Import_Symbol_location_<Not_Shared>_120258_120244'].geometry}
              material={nodes['Import_Symbol_location_<Not_Shared>_120258_120244'].material}
              userData={{ name: 'Import Symbol location <Not Shared> [120258]_[120244]' }}
            />
            <mesh
              name="Import_Symbol_location_<Not_Shared>_120258_120245"
              castShadow
              receiveShadow
              geometry={nodes['Import_Symbol_location_<Not_Shared>_120258_120245'].geometry}
              material={nodes['Import_Symbol_location_<Not_Shared>_120258_120245'].material}
              userData={{ name: 'Import Symbol location <Not Shared> [120258]_[120245]' }}
            />
          </group>
        </mesh>
        <mesh
          name="Object011001"
          castShadow
          receiveShadow
          geometry={nodes.Object011001.geometry}
          material={nodes.Object011001.material}
          position={[0.05005138, -0.0366092, -0.52212274]}
          rotation={[Math.PI / 2, 2.8e-7, 0.54610329]}
          scale={[1.02415085, 1.02415049, 1.02415049]}
          userData={{ name: 'Object011.001' }}
        />
        <mesh
          name="Salt_House_Cafe_Logo_without_Background_PNG"
          castShadow
          receiveShadow
          geometry={nodes.Salt_House_Cafe_Logo_without_Background_PNG.geometry}
          material={materials['Salt House Cafe Logo without Background PNG']}
          position={[-0.18374655, 1.20939946, -0.64132136]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.70468074, 0.70468074, 0.70468074]}
          userData={{ name: 'Salt House Cafe Logo without Background PNG' }}
        />
        <mesh
          name="29_Vitra_Eames_Plastic_Side_chair_DSR005002"
          castShadow
          receiveShadow
          geometry={nodes['29_Vitra_Eames_Plastic_Side_chair_DSR005002'].geometry}
          material={nodes['29_Vitra_Eames_Plastic_Side_chair_DSR005002'].material}
          position={[-1.05351913, 0.02323057, 1.03537405]}
          rotation={[Math.PI / 2, -3.8e-7, -1.47416093]}
          scale={[1.04051912, 1.04051876, 1.04051876]}
          userData={{ name: '29_Vitra_Eames_Plastic_Side_chair_DSR005.002' }}
        />
        <mesh
          name="29_Vitra_Eames_Plastic_Side_chair_DSR005001"
          castShadow
          receiveShadow
          geometry={nodes['29_Vitra_Eames_Plastic_Side_chair_DSR005001'].geometry}
          material={nodes['29_Vitra_Eames_Plastic_Side_chair_DSR005001'].material}
          position={[0.05005138, -0.0366092, -0.52212274]}
          rotation={[Math.PI / 2, 2.8e-7, 0.54610329]}
          scale={[1.02415085, 1.02415049, 1.02415049]}
          userData={{ name: '29_Vitra_Eames_Plastic_Side_chair_DSR005.001' }}
        />
        <mesh
          name="grass-gc4a111c28_1920"
          castShadow
          receiveShadow
          geometry={nodes['grass-gc4a111c28_1920'].geometry}
          material={materials['grass-gc4a111c28_1920']}
          position={[-0.13397095, -0.01784811, 0.47236192]}
          scale={[1.83650923, 2.02528477, 2.40283608]}
          userData={{ name: 'grass-gc4a111c28_1920' }}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/samplenew.glb')
